import rawLogoMark from "@/assets/logos/mark.svg";
import rawLogoWordmark from "@/assets/logos/wordmark.svg";
import rawLogoMarkLight from "@/assets/logos/mark-light.svg";
import rawLogoWordmarkLight from "@/assets/logos/wordmark-light.svg";
import rawSteth1 from "@/assets/hero/steth-1.svg";
import rawSteth2 from "@/assets/hero/steth-2.svg";
import rawSteth3 from "@/assets/hero/steth-3.svg";
import rawSteth4 from "@/assets/hero/steth-4.svg";
import rawSteth5 from "@/assets/hero/steth-5.svg";
import rawDoctor from "@/assets/hero/doctor.png";
import rawDoctorMask from "@/assets/hero/doctor-mask.svg";
import rawHeroOutline from "@/assets/hero/outline.svg";
import rawHeroCircle from "@/assets/hero/circle.svg";
import rawHeroShape from "@/assets/hero/shape.svg";
import rawBadgeGlow from "@/assets/hero/badge-glow.svg";
import rawInsurerOwlexa from "@/assets/insurers/owlexa.png";
import rawInsurerBcaLife from "@/assets/insurers/bca-life.png";
import rawInsurerMandiriInhealth from "@/assets/insurers/mandiri-inhealth.png";
import rawInsurerPln from "@/assets/insurers/pln.png";
import rawInsurerBniLife from "@/assets/insurers/bni-life.png";
import rawInsurerBni from "@/assets/insurers/bni.png";
import rawInsurerAdmedika from "@/assets/insurers/admedika.png";
import rawInsurerTelkomedika from "@/assets/insurers/telkomedika.png";
import rawInsurerBriLife from "@/assets/insurers/bri-life.png";
import rawInsurerBri from "@/assets/insurers/bri.png";
import rawInsurerYkkbi from "@/assets/insurers/ykkbi.png";
import rawIconArrow from "@/assets/icons/arrow-right.svg";
import rawIconServiceAnak from "@/assets/icons/service-anak.svg";
import rawIconCircleGreen from "@/assets/icons/circle-green.svg";
import rawIconPregnant from "@/assets/icons/pregnant.svg";
import rawIconCirclePink from "@/assets/icons/circle-pink.svg";
import rawIconSkin from "@/assets/icons/skin.svg";
import rawIconCircleLilac from "@/assets/icons/circle-lilac.svg";
import rawIconEar from "@/assets/icons/ear.svg";
import rawIconServiceSaraf from "@/assets/icons/service-saraf.svg";
import rawIconServiceJiwa from "@/assets/icons/service-jiwa.svg";
import rawIconCircleBlue from "@/assets/icons/circle-blue.svg";
import rawIconUserSearch from "@/assets/icons/user-search.svg";
import rawIconFacilityAdmin from "@/assets/icons/facility-admin.svg";
import rawIconFacilityWait from "@/assets/icons/facility-wait.svg";
import rawIconFacilityNurse from "@/assets/icons/facility-nurse.svg";
import rawIconFacilityDoctor from "@/assets/icons/facility-doctor.svg";
import rawIconToilet from "@/assets/icons/toilet.svg";
import rawIconCalendar from "@/assets/icons/calendar.svg";
import rawIconWhatsappWhite from "@/assets/icons/whatsapp-white.svg";
import rawIconTimer from "@/assets/icons/timer.svg";
import rawIconWhatsappPink from "@/assets/icons/whatsapp-pink.svg";
import rawIconInstagram from "@/assets/icons/instagram.svg";
import rawIconFacebook from "@/assets/icons/facebook.svg";
import rawIconWhatsapp from "@/assets/icons/whatsapp.svg";
import rawIconNurse from "@/assets/icons/nurse.svg";
import rawIconGigi from "@/assets/icons/gigi.svg";
import rawIconPregnantLayanan from "@/assets/icons/pregnant-layanan.svg";
import rawIconPenyakitDalam from "@/assets/icons/penyakit-dalam.svg";
import rawIconParu from "@/assets/icons/paru.svg";
import rawIconCircleMint from "@/assets/icons/circle-mint.svg";
import rawIconHandSanitizer from "@/assets/icons/hand-sanitizer.svg";
import rawIconCircleRed from "@/assets/icons/circle-red.svg";
import rawIconFire from "@/assets/icons/fire.svg";
import rawIconFacilityCctv from "@/assets/icons/facility-cctv.svg";
import rawIconFacilityNoSmoking from "@/assets/icons/facility-no-smoking.svg";
import rawPromoClinic from "@/assets/photos/promo-clinic.png";
import rawBannerTexture from "@/assets/photos/banner-texture.png";
import rawBannerFamily from "@/assets/photos/banner-family.png";

function url(file: string | { src: string }) {
  return typeof file === "string" ? file : file.src;
}

export const logoMark = url(rawLogoMark);
export const logoWordmark = url(rawLogoWordmark);
export const logoMarkLight = url(rawLogoMarkLight);
export const logoWordmarkLight = url(rawLogoWordmarkLight);
export const steth1 = url(rawSteth1);
export const steth2 = url(rawSteth2);
export const steth3 = url(rawSteth3);
export const steth4 = url(rawSteth4);
export const steth5 = url(rawSteth5);
export const iconArrow = url(rawIconArrow);
export const doctor = url(rawDoctor);
export const doctorMask = url(rawDoctorMask);
export const heroOutline = url(rawHeroOutline);
export const heroCircle = url(rawHeroCircle);
export const heroShape = url(rawHeroShape);
export const badgeGlow = url(rawBadgeGlow);
export const insurerOwlexa = url(rawInsurerOwlexa);
export const insurerBcaLife = url(rawInsurerBcaLife);
export const insurerMandiriInhealth = url(rawInsurerMandiriInhealth);
export const insurerPln = url(rawInsurerPln);
export const insurerBniLife = url(rawInsurerBniLife);
export const insurerBni = url(rawInsurerBni);
export const insurerAdmedika = url(rawInsurerAdmedika);
export const insurerTelkomedika = url(rawInsurerTelkomedika);
export const insurerBriLife = url(rawInsurerBriLife);
export const insurerBri = url(rawInsurerBri);
export const insurerYkkbi = url(rawInsurerYkkbi);
export const iconServiceAnak = url(rawIconServiceAnak);
export const iconCircleGreen = url(rawIconCircleGreen);
export const iconPregnant = url(rawIconPregnant);
export const iconCirclePink = url(rawIconCirclePink);
export const iconSkin = url(rawIconSkin);
export const iconCircleLilac = url(rawIconCircleLilac);
export const iconEar = url(rawIconEar);
export const iconServiceSaraf = url(rawIconServiceSaraf);
export const iconServiceJiwa = url(rawIconServiceJiwa);
export const iconCircleBlue = url(rawIconCircleBlue);
export const iconUserSearch = url(rawIconUserSearch);
export const iconFacilityAdmin = url(rawIconFacilityAdmin);
export const iconFacilityWait = url(rawIconFacilityWait);
export const iconFacilityNurse = url(rawIconFacilityNurse);
export const iconFacilityDoctor = url(rawIconFacilityDoctor);
export const iconToilet = url(rawIconToilet);
export const promoClinic = url(rawPromoClinic);
export const iconCalendar = url(rawIconCalendar);
export const iconWhatsappWhite = url(rawIconWhatsappWhite);
export const iconTimer = url(rawIconTimer);
export const bannerTexture = url(rawBannerTexture);
export const bannerFamily = url(rawBannerFamily);
export const iconWhatsappPink = url(rawIconWhatsappPink);
export const iconInstagram = url(rawIconInstagram);
export const iconFacebook = url(rawIconFacebook);
export const iconWhatsapp = url(rawIconWhatsapp);
export const iconNurse = url(rawIconNurse);
export const iconGigi = url(rawIconGigi);
export const iconPregnantLayanan = url(rawIconPregnantLayanan);
export const iconPenyakitDalam = url(rawIconPenyakitDalam);
export const iconParu = url(rawIconParu);
export const iconCircleMint = url(rawIconCircleMint);
export const iconHandSanitizer = url(rawIconHandSanitizer);
export const iconCircleRed = url(rawIconCircleRed);
export const iconFire = url(rawIconFire);
export const iconFacilityCctv = url(rawIconFacilityCctv);
export const iconFacilityNoSmoking = url(rawIconFacilityNoSmoking);
